### ISSUE TITLE
Setting to test mode does not route to dev environment.

### ISSUE THREAD

**Issue by rlcooper46** [rocketgate/rocketgate-go-sdk#2]
I believe there is a reference issue when setting test mode in service.go
https://github.com/rocketgate/rocketgate-go-sdk/blob/1639c0c82738bcbe02aaf8c7f37043181ef771d8/service/service.go#L197

The change to the service's variables is not being applied due to the GatewayService not being passed by pointer.

**Comment by rlcooper46** [comment]
Have submitted a fix in #3

**Comment by rgflight** [comment]
thanks, dev submitted fix along with others in fix 4
