### ISSUE TITLE
Support custom http clients

### ISSUE THREAD

**Issue by rlcooper46** [rocketgate/rocketgate-go-sdk#5]
We are requesting support for custom http client implementations in GatewayService.

Right now, their are existing functions to change the host via SetHost, timeouts via SetTimeout, etc.

We are requesting an additional function SetHttpClient(*http.Client). This will override the client used to perform the http request in performTransactionServer. 

Thank you!

**Comment by rlcooper46** [comment]
https://github.com/rocketgate/rocketgate-go-sdk/blob/c85f16d1e9f33f6639f2d78798b95f99eb7d8839/service/service.go#L404

We wish to override this client

**Comment by rgflight** [comment]
Can you please advise a bit more on why you would want to do that.... 
We provide functions for things like SetTimeout because merchants might want to change that...is there something specific you want? we could add a method to support it?

One idea of the SDK is that it's easy to support by us because it is a common implementation, a complete override over the http client would render that impossible.

**Comment by rlcooper46** [comment]
Hi @rgflight 

Thanks for looking into this. 

It is a common feature among web SDKs to allow users to define the http client that will be used for transactions. In our scenario, this is absolutely necessary as we have logging/scrubbing/proxying tools integrated directly with an http client we use for all API transactions. 

We also integrate with a variety of payment processor SDKs, and this is a common feature among all of them. 
See Adyen for example: https://github.com/Adyen/adyen-go-api-library/blob/94a833a4a747870a331e220c102cb78ca508e5ca/src/common/configuration.go#L92
See

**Comment by rgflight** [comment]
understood, thanks for the explanation, i added some more of our dev team, they understand, are discussing, and should respond. obviously a holiday week so might be a few days.

**Comment by rlcooper46** [comment]
Hi @rgflight,

Hope holidays went well! Just bumping this as this is necessary for our integration with this SDK.

Thanks

**Comment by rgflight** [comment]
dev team agreed and merged.
